/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.andriigubarenko.beatbox;

import java.awt.Label;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Vector;
import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MidiEvent;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.MidiUnavailableException;
import javax.sound.midi.Sequence;
import javax.sound.midi.Sequencer;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.Track;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;

/**
 *
 * @author Андрей
 */
public class BeatBoxGui extends javax.swing.JFrame {

    /**
     * Creates new form BeatBoxGui
     */
    int nextNum;
    ObjectInputStream in;
    ObjectOutputStream out;
    String userName;
    Vector<String> listVector = new Vector<>();
    HashMap<String, boolean[]> otherSeqsMap = new HashMap<>();
    ArrayList<JCheckBox> checkboxList = new ArrayList<>();
    Sequencer sequencer;
    Sequence sequence;
    Sequence mySequence = null;
    Track track;

    int[] instruments = {35, 42, 46, 38, 49, 39, 50, 60, 70, 72, 64, 56, 58, 47, 67, 63};
    String[] instrumentNames = {"Bass Drum", "Closed Hi-Hat",
        "Open Hi-Hat", "Acoustic Snare", "Crash Cymbal", "Hand Clap",
        "High Tom", "Hi Bongo", "Maracas", "Whistle", "Low Conga",
        "Cowbell", "Vibraslap", "Low-mid Tom", "High Agogo",
        "Open Hi Conga"};

    public BeatBoxGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        loadIt = new javax.swing.JButton();
        saveIt = new javax.swing.JButton();
        sendIt = new javax.swing.JButton();
        downTempo = new javax.swing.JButton();
        upTempo = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        start = new javax.swing.JButton();
        userMessage = new javax.swing.JTextField();
        nameBox = new javax.swing.JPanel();
        theList = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        incomingList = new javax.swing.JList<>();
        grid = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 430));
        setMinimumSize(new java.awt.Dimension(800, 430));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 5, 50, 20));

        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeMouseReleased(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 6, 50, 20));

        loadIt.setText("Load File");
        loadIt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loadIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadItActionPerformed(evt);
            }
        });
        getContentPane().add(loadIt, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 201, 110, 25));

        saveIt.setText("Save It");
        saveIt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItActionPerformed(evt);
            }
        });
        getContentPane().add(saveIt, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 174, 110, 25));

        sendIt.setText("Send It");
        sendIt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendItActionPerformed(evt);
            }
        });
        getContentPane().add(sendIt, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 147, 110, 25));

        downTempo.setText("Temp Down");
        downTempo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        downTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downTempoActionPerformed(evt);
            }
        });
        getContentPane().add(downTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 121, 110, 25));

        upTempo.setText("Temp Up");
        upTempo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upTempoActionPerformed(evt);
            }
        });
        getContentPane().add(upTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 94, 110, 25));

        stop.setText("Stop");
        stop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        getContentPane().add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 67, 110, 25));

        start.setText("Start");
        start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 40, 110, 25));
        getContentPane().add(userMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 234, 255, 50));

        for (int i = 0; i < 16; i++) {
            nameBox.add(new Label(instrumentNames[i]));
        }
        nameBox.setBackground(new java.awt.Color(52, 73, 94));
        getContentPane().add(nameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 36, 100, 375));

        incomingList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                incomingListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(incomingList);

        theList.add(jScrollPane1);

        getContentPane().add(theList, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 292, 255, 120));

        grid.setBackground(new java.awt.Color(52, 73, 94));
        grid.setForeground(new java.awt.Color(52, 73, 94));
        grid.setToolTipText("");
        grid.setMaximumSize(new java.awt.Dimension(400, 388));
        grid.setMinimumSize(new java.awt.Dimension(400, 388));
        grid.setLayout(new java.awt.GridLayout(16, 16, 2, 1));
        getContentPane().add(grid, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 34, 400, 386));
        for (int i = 0; i < 256; i++) {
            JCheckBox c = new JCheckBox();
            c.setBackground(new java.awt.Color(52, 73, 94));
            c.setSelected(false);
            checkboxList.add(c);
            grid.add(c);
        }

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/andriigubarenko/images/Gui_view.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        System.exit(0);
    }//GEN-LAST:event_closeMouseReleased

    private void minimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseReleased
        this.setState(BeatBoxGui.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseReleased

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        buildTrackAndStart();
    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        sequencer.stop();
    }//GEN-LAST:event_stopActionPerformed

    private void upTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upTempoActionPerformed
        float tempoFactor = sequencer.getTempoFactor();
        sequencer.setTempoFactor((float) (tempoFactor * 1.03));
    }//GEN-LAST:event_upTempoActionPerformed

    private void downTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downTempoActionPerformed
        float tempoFactor = sequencer.getTempoFactor();
        sequencer.setTempoFactor((float) (tempoFactor * .97));
    }//GEN-LAST:event_downTempoActionPerformed

    private void sendItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendItActionPerformed
        // make an arraylist of just the STATE of the checkboxes
        boolean[] checkboxState = new boolean[256];

        for (int i = 0; i < 256; i++) {
            JCheckBox check = (JCheckBox) checkboxList.get(i);
            if (check.isSelected()) {
                checkboxState[i] = true;
            }
        }

        try {
            out.writeObject(userName + nextNum++ + ": " + userMessage.getText());
            out.writeObject(checkboxState);
        } catch (IOException ex) {
            ex.printStackTrace();
            System.out.println("sorry dude. Could not send it to the server");
        }
    }//GEN-LAST:event_sendItActionPerformed

    private void saveItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItActionPerformed
        JFileChooser fileSave = new JFileChooser();
        fileSave.showSaveDialog(this);
        saveFile(fileSave.getSelectedFile());
    }

    private void saveFile(File file) {
        boolean[] checkboxState = new boolean[256];
        for (int i = 0; i < 256; i++) {
            JCheckBox check = (JCheckBox) checkboxList.get(i);
            if (check.isSelected()) {
                checkboxState[i] = true;
            }
        }
        try {
            FileOutputStream fileStream = new FileOutputStream(file);
            ObjectOutputStream os = new ObjectOutputStream(fileStream);
            os.writeObject(checkboxState);
            os.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_saveItActionPerformed

    private void loadItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadItActionPerformed
        JFileChooser fileOpen = new JFileChooser();
        fileOpen.showOpenDialog(this);
        loadFile(fileOpen.getSelectedFile());
    }

    private void loadFile(File file) {
        boolean[] checkboxState = null;
        try {
            FileInputStream fileIn = new FileInputStream(file);
            ObjectInputStream is = new ObjectInputStream(fileIn);
            checkboxState = (boolean[]) is.readObject();
            is.close();
        } catch (IOException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        for (int i = 0; i < 256; i++) {
            JCheckBox check = (JCheckBox) (checkboxList.get(i));
            if (checkboxState[i] != false) {
                check.setSelected(true);
            } else {
                check.setSelected(false);
            }
        }
        sequencer.stop();
        buildTrackAndStart();
    }//GEN-LAST:event_loadItActionPerformed

    private void incomingListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_incomingListValueChanged

        if (!evt.getValueIsAdjusting()) {
            String selected = (String) incomingList.getSelectedValue();
            if (selected != null) {
                boolean[] selectedState = (boolean[]) otherSeqsMap.get(selected);
                changeSequence(selectedState);
                sequencer.stop();
                buildTrackAndStart();
            }
        }
    }//GEN-LAST:event_incomingListValueChanged

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
 /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeatBoxGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeatBoxGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeatBoxGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeatBoxGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /* java.awt.EventQueue.invokeLater(() -> {
            new BeatBoxGui().setVisible(true);
        });
    }*/

    //=======================================================================
    public void startUp(String name) {
        userName = name;
        try {
            Socket sock = new Socket("127.0.0.1", 4242);
            out = new ObjectOutputStream(sock.getOutputStream());
            in = new ObjectInputStream(sock.getInputStream());
            Thread remote = new Thread(new RemoteReader());
            remote.start();
        } catch (IOException ex) {
            System.out.println("couldn't connect - you'll have to play alone.");
        }
        setUpMidi();
    }

    public void setUpMidi() {
        try {
            sequencer = MidiSystem.getSequencer();
            sequencer.open();
            //sequencer.addMetaEventListener(this);
            sequence = new Sequence(Sequence.PPQ, 4);
            track = sequence.createTrack();
            sequencer.setTempoInBPM(120);

        } catch (InvalidMidiDataException | MidiUnavailableException e) {
            e.printStackTrace();
        }
    } // close method

    public void buildTrackAndStart() {
        // this will hold the instruments for each vertical column,
        // in other words, each tick (may have multiple instruments)
        ArrayList<Integer> trackList = null;

        sequence.deleteTrack(track);
        track = sequence.createTrack();

        for (int i = 0; i < 16; i++) {
            trackList = new ArrayList<>();
            for (int j = 0; j < 16; j++) {
                JCheckBox jc = (JCheckBox) checkboxList.get(j + (16 * i));
                if (jc.isSelected()) {
                    int key = instruments[i];
                    trackList.add(key);
                } else {
                    trackList.add(null);
                }
            } // close inner

            makeTracks(trackList);
        } // close outer

        track.add(makeEvent(192, 9, 1, 0, 15)); // - so we always go to full 16 beats

        try {

            sequencer.setSequence(sequence);
            sequencer.setLoopCount(sequencer.LOOP_CONTINUOUSLY);
            sequencer.start();
            sequencer.setTempoInBPM(120);
        } catch (InvalidMidiDataException e) {
            e.printStackTrace();
        }

    } // close method

//============================================================== inner class listeners           
    public class RemoteReader implements Runnable {

        boolean[] checkboxState = null;
        String nameToShow = null;
        Object obj = null;

        @Override
        public void run() {
            try {
                while ((obj = in.readObject()) != null) {
                    System.out.println("got an object from server");
                    System.out.println(obj.getClass());
                    String nameToShow = (String) obj;
                    checkboxState = (boolean[]) in.readObject();
                    otherSeqsMap.put(nameToShow, checkboxState);
                    listVector.add(nameToShow);
                    incomingList.setListData(listVector);
                }
            } catch (IOException | ClassNotFoundException e) {
                e.printStackTrace();
            }
        }
    }

//==============================================================       
    public void changeSequence(boolean[] checkboxState) {
        for (int i = 0; i < 256; i++) {
            JCheckBox check = (JCheckBox) checkboxList.get(i);
            if (checkboxState[i]) {
                check.setSelected(true);
            } else {
                check.setSelected(false);
            }
        }
    }

    public void makeTracks(ArrayList<Integer> list) {
        Iterator it = list.iterator();
        for (int i = 0; i < 16; i++) {
            Integer num = (Integer) it.next();
            if (num != null) {
                int numKey = num.intValue();
                track.add(makeEvent(144, 9, numKey, 100, i));
                track.add(makeEvent(128, 9, numKey, 100, i + 1));
            }
        }
    }

    public MidiEvent makeEvent(int comd, int chan, int one, int two, int tick) {
        MidiEvent event = null;
        try {
            ShortMessage a = new ShortMessage();
            a.setMessage(comd, chan, one, two);
            event = new MidiEvent(a, tick);

        } catch (InvalidMidiDataException e) {
        }
        return event;
    }
    //======================================================================

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel close;
    private javax.swing.JButton downTempo;
    private javax.swing.JPanel grid;
    private javax.swing.JList<String> incomingList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadIt;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel nameBox;
    private javax.swing.JButton saveIt;
    private javax.swing.JButton sendIt;
    private javax.swing.JButton start;
    private javax.swing.JButton stop;
    private java.awt.ScrollPane theList;
    private javax.swing.JButton upTempo;
    private javax.swing.JTextField userMessage;
    // End of variables declaration//GEN-END:variables
}
